### ISSUE TITLE
Activity indicator does not show up if add "use_frameworks!" in pod file

### ISSUE THREAD

**Issue by DimonDeveloper** [TaimurAyaz/TAOverlay#12]
Do not show activity indicator if "use_frameworks!" in pod file

**Comment by skela** [comment]
I think he means to say that the activity indicator does not show up when used as a framework with cocoapods (i.e. if the Podfile has use_frameworks!).

I'm seeing the same issue here, just noticed it after switching to frameworks.

**Comment by skela** [comment]
I've fixed the issue here in this pull request: https://github.com/TaimurAyaz/TAOverlay/pull/18
