### ISSUE TITLE
Mutable Properties

### ISSUE THREAD

**Issue by cytryn** [TaimurAyaz/TAOverlay#2]
Anyway you can add properties so we can change background color, font, font color?

**Comment by TaimurAyaz** [comment]
That is on my todo. Should be up soon!

**Comment by TaimurAyaz** [comment]
Added!

**Comment by cytryn** [comment]
Awesome, thanks!

**Comment by cytryn** [comment]
How exactly am I supposed to access those properties?

Can't find them on the .h of version 1.3

**Comment by TaimurAyaz** [comment]
I have yet to update the demo project but the properties are available at the source folder at root

**Comment by TaimurAyaz** [comment]
Acutally, I just checked. The properties should be there since my last push.

**Comment by cytryn** [comment]
need to update pod maybe?

**Comment by cytryn** [comment]
Just pulled from the github instead of cocoapods and could not get this working...

Could you please add some of this functionality in the example project?

**Comment by TaimurAyaz** [comment]
Hey I will push an update in a bit. It should be included in that.

**Comment by TaimurAyaz** [comment]
It should work now.

**Comment by TaimurAyaz** [comment]
I will update the demo project in a bit
