### ISSUE TITLE
Dismiss on tap

### ISSUE THREAD

**Issue by cytryn** [TaimurAyaz/TAOverlay#3]
Would be a great feature let the user dismiss the overlay by tapping (gesture) on it.

**Comment by TaimurAyaz** [comment]
That is a great suggestion:) should be up soon.

**Comment by sadhiappan** [comment]
Great Control!
Would love this feature. Pull down/push up to dismiss in case of full screen, maybe.

**Comment by TaimurAyaz** [comment]
Working on that. Expect it to be up soon.

**Comment by TaimurAyaz** [comment]
Tap and swipe gestures are up. Consult README for details on which options to put for the gestures.
