### ISSUE TITLE
Overlay queue

### ISSUE THREAD

**Issue by cytryn** [TaimurAyaz/TAOverlay#4]
Also a great feature to have, queue some overlays would be great....

**Comment by TaimurAyaz** [comment]
Hmm. I am not convinced by this one. I mean, what could be a real world use of this? As a user I would find it pretty annoying.

**Comment by cytryn** [comment]
If there are more than two error messages I want to show...

**Comment by TaimurAyaz** [comment]
I see your point. Ill add it soon.

**Comment by cytryn** [comment]
A more specific example:
User hits login button
I show the overlay with a spinner
When return block of the login is called I hide the the overlay.
If success do nothing, but if error I want to show another overlay with the error message.

But both get dismissed.

**Comment by TaimurAyaz** [comment]
That senario should work. You could always call the show method again to change the overlay and since its called on the shared instance of the overlay, you are essentially changing the same overlay.

**Comment by TaimurAyaz** [comment]
I see what you mean. Since the overlay adopts the singleton pattern, only one instance is available during the lifetime of the application and this you cannot shows multiple overlays at once. You could show multiple overlays in succession, which would essentially be the same as I explained above.

**Comment by TaimurAyaz** [comment]
I guess I will shelve this for now, in favour of other features. You are welcome to send a pull request if you get this working before me.

**Comment by cytryn** [comment]
Ok, I will see if I have some time for that.

But just to let you know, I would already use it right know because I already get both my overlays dismissed at the same time =/

**Comment by TaimurAyaz** [comment]
Are you using an overlay with the "auto hide" option? The auto hide option overwrites and hide call, currently. I will be pushing an update where the auto hide option is overwritten by the hide call.
