### ISSUE TITLE
Cocoapods Trunk contains invalid info on this project

### ISSUE THREAD

**Issue by tayhalla** [TaimurAyaz/TAOverlay#5]
If you search for this project via CocoaPods:
`pod search TAoverlay`

It returns a pod entry that is versioned to `1.2.1`, the latest available version on this repo is far less than that. Just a heads up. 

Nice project!

**Comment by TaimurAyaz** [comment]
Thanks :+1:   I uploaded multiple versions while trying to get cocoapods to work. Not sure how to get that removed. The official version should be 1.0.1. I am looking into this. Any help welcome.

**Comment by TaimurAyaz** [comment]
So I pushed v1.3. It should now be similar in both places. It should show up in a bit.

**Comment by TaimurAyaz** [comment]
FIXED
