### ISSUE TITLE
Overlay-type icon colour

### ISSUE THREAD

**Issue by skela** [TaimurAyaz/TAOverlay#7]
Love this library :D

Just wondering if it would be a good idea to offer us the ability to override the colours you use for your icons. Maybe something like : [TAOverlay setOverlayIconColor:[UIColor whiteColor]];

**Comment by skela** [comment]
Figured out how to do it, but will leave this issue open in case you think it might be a good idea anyway.

```
TAOverlayOptions options = TAOverlayOptionOverlayTypeInfo | TAOverlayOptionOverlayDismissTap;
[TAOverlay showOverlayWithLabel:@"This is my info, hope you like it" Options:options];
UIColor *color = [UIColor whiteColor];
[TAOverlay setOverlayLabelTextColor:color];
[[[TAOverlay shared] icon] setFillColor:color.CGColor];
[[[TAOverlay shared] icon] setBorderColor:color.CGColor];
```

**Comment by TaimurAyaz** [comment]
Thanks :) I am working on those. Should be up by the weekend!

**Comment by TaimurAyaz** [comment]
Sorry for the delay! I added the customization methods! Also added some other sweet improvements. Check the README :)
