### ISSUE TITLE
Center in a ViewController

### ISSUE THREAD

**Issue by fethica** [TaimurAyaz/TAOverlay#8]
I'm using it to load data in a UISplitViewController, is there a way to center it in the detail view controller instead of the entire window (iPad) ?

Thank you !

**Comment by TaimurAyaz** [comment]
Not yet! but that's a great idea! I will definitely add that in a future release :)

**Comment by TaimurAyaz** [comment]
I will be updating the control in the coming weeks. This feature would be included!

**Comment by fethica** [comment]
Thank you :+1:
