### ISSUE TITLE
Customization for Activity Indicator

### ISSUE THREAD

**Issue by idec** [TaimurAyaz/TAOverlay#9]
First of all, congratulations for this library, is awesome! :D

Playing with it I found out that you can't change the color of the Activity Indicators, I mean you can change the color in TAOverlay.h but there is not a method like setOverlayIconColor: for that so I think it might be a good idea if it is possible!

Again, great job!

**Comment by TaimurAyaz** [comment]
Hey Thanks for the complement :)

I will be updating the library in the coming weeks. This and more awesome stuff would be included!
